apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod-volume
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/config
          readOnly: true
      ports:
      - containerPort: 80
  volumes:
    - name: secret-volume
      secret:
        secretName: mysecret