apiVersion: v1
kind: Config
clusters:
- name: {cluster-name}
  cluster:
    certificate-authority-data: {cluster-ca}
    server: {server-dns}
users:
- name: {user-name}
  user:
    token: {secret-token}
 
contexts:
- name: {context-name}
  context:
    cluster: {cluster-name}
    user: {user-name}
    namespace: {name-namespace}
current-context: {context-name}

