apiVersion: v1
kind: Pod
metadata:
  name: pod1-test
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "800Mi"
        cpu: "1000m"
      requests:
        memory: "600Mi"
        cpu: "350m"
---
# this pod won't be created
apiVersion: v1
kind: Pod
metadata:
  name: pod2-test
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "300Mi"
        cpu: "500m"
      requests:
        memory: "200Mi"
        cpu: "350m"