apiVersion: v1
kind: Pod
metadata:
  name: pod-change-time
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sh", "-c", "sleep 3600"]
    securityContext:
      capabilities:
        add:
        - SYS_TIME