apiVersion: v1
kind: Pod
metadata:
  name: pod-run-as-non-root
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sh", "-c", "sleep 3600"]
    securityContext:
      runAsNonRoot: true