apiVersion: v1
kind: Pod
metadata:
  name: pod-remove-chown
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sh", "-c", "sleep 3600"]
    securityContext:
      capabilities:
        drop:
        - CHOWN