apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  securityContext:   # Pod-level security context
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - name: secure-container
    image: alpine
    command: ["/bin/sh", "-c", "sleep 3600"]
    securityContext:  # Container-level security context
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]