apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: pod-manager
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "list", "delete"]
#  - apiGroups: ["apps"]
#    resources: ["deployment"]
#    verbs: ["create", "get", "update", "list", "delete", "watch", "patch"]
#  - apiGroups: ["rbac.authorization.k8s.io"]
#    resources: ["clusterroles", "clusterrolebindings"]
#    verbs: ["create", "get", "list", "watch"]
---
# create a rolebinding for a user called adam
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: dev
subjects:
- kind: User
  name: Adam
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io