apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Only one node can mount the volume
  resources:
    requests:
      storage: 5Gi  # Request 5GB of storage
  storageClassName: gp2  # Default StorageClass for EBS in AWS
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-ebs
spec:
  containers:
  - name: app
    image: busybox
    command: [ "sh", "-c", "echo 'Hello from EBS!' > /data/test.txt && sleep 3600" ]
    volumeMounts:
    - mountPath: "/data"
      name: storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: ebs-pvc
#
# Dynamic provisioning for ebs volumes must be enabled in the cluster
# Create the resources in the cluster
#
# kubectl apply -f ebs-pvc-pod.yaml
#
# Verify that the PVC status is **Bound** and that the pod is running and using the volume
#
# kubectl get pvc
# kubectl get pod
# kubectl exec -it pod-ebs -- cat /data/test.txt
#
# delete the resources
# kubectl delete -f ebs-pvc-pod.yaml