apiVersion: v1
kind: Pod
metadata:
 name: utrains
spec:
 containers:
   - name: utrains-app
     image: httpd
#
#
# Here we create a simple pod that will run apache (httpd image)
# This pod will be created in the default namespace since no namespace was specified
#
# create the file for the pod
# vi 01-simple-pod.yaml
#
# deploy the pod in the cluster
# kubectl create -f 01-simple-pod.yaml
#
# verify
# kubectl get pods
#
# delete pod
# kubectl delete pods utrains